# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-28 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favorit',
            new_name='is_favorite',
        ),
    ]
